pub const XHCI_HOST_CONTROLLER_MAX_COUNT: usize = 4;
pub const INTERRUPT_VECTOR_XHCI_SLOT_0: u8 = 0x40;
pub const INTERRUPT_VECTOR_XHCI_SLOT_1: u8 = 0x41;
pub const INTERRUPT_VECTOR_XHCI_SLOT_2: u8 = 0x42;
pub const INTERRUPT_VECTOR_XHCI_SLOT_3: u8 = 0x43;
pub const INTERRUPT_VECTOR_LOCAL_APIC_TIMER: u8 = 0x60;
