pub const DESCRIPTOR_TYPE_UPPER_8_BYTES: u8 = 0;
pub const DESCRIPTOR_TYPE_READ_WRITE: u8 = 2;
pub const DESCRIPTOR_TYPE_TSS_AVAILABLE: u8 = 9;
pub const DESCRIPTOR_TYPE_EXECUTE_READ: u8 = 10;
pub const DESCRIPTOR_TYPE_TSS_BUSY: u8 = 11;
pub const DESCRIPTOR_TYPE_CALL_GATE: u8 = 12;
pub const DESCRIPTOR_TYPE_INTERRUPT_GATE: u8 = 14;
pub const DESCRIPTOR_TYPE_TRAP_GATE: u8 = 15;
