use crate::uefi::data_type::basic_type::EFI_GRAPHICS_PIXEL_FORMAT;

pub const PIXEL_RED_GREEN_BLUE_RESERVED8_BIT_PER_COLOR: EFI_GRAPHICS_PIXEL_FORMAT = 0;
pub const PIXEL_BLUE_GREEN_RED_RESERVED8_BIT_PER_COLOR: EFI_GRAPHICS_PIXEL_FORMAT = 1;
pub const PIXEL_BIT_MASK: EFI_GRAPHICS_PIXEL_FORMAT = 2;
pub const PIXEL_BLT_ONLY: EFI_GRAPHICS_PIXEL_FORMAT = 3;
pub const PIXEL_FORMAT_MAX: EFI_GRAPHICS_PIXEL_FORMAT = 4;
