use crate::uefi::data_type::basic_type::EFI_MEMORY_TYPE;

pub const EFI_RESERVED_MEMORY_TYPE: EFI_MEMORY_TYPE = 0;
pub const EFI_LOADER_CODE: EFI_MEMORY_TYPE = 1;
pub const EFI_LOADER_DATA: EFI_MEMORY_TYPE = 2;
pub const EFI_BOOT_SERVICES_CODE: EFI_MEMORY_TYPE = 3;
pub const EFI_BOOT_SERVICES_DATA: EFI_MEMORY_TYPE = 4;
pub const EFI_RUNTIME_SERVICES_CODE: EFI_MEMORY_TYPE = 5;
pub const EFI_RUNTIME_SERVICES_DATA: EFI_MEMORY_TYPE = 6;
pub const EFI_CONVENTIONAL_MEMORY: EFI_MEMORY_TYPE = 7;
pub const EFI_UNUSABLE_MEMORY: EFI_MEMORY_TYPE = 8;
pub const EFI_ACPIRECLAIM_MEMORY: EFI_MEMORY_TYPE = 9;
pub const EFI_ACPIMEMORY_NVS: EFI_MEMORY_TYPE = 10;
pub const EFI_MEMORY_MAPPED_IO: EFI_MEMORY_TYPE = 11;
pub const EFI_MEMORY_MAPPED_IOPORT_SPACE: EFI_MEMORY_TYPE = 12;
pub const EFI_PAL_CODE: EFI_MEMORY_TYPE = 13;
pub const EFI_PERSISTENT_MEMORY: EFI_MEMORY_TYPE = 14;
pub const EFI_UNACCEPTED_MEMORY_TYPE: EFI_MEMORY_TYPE = 15;
pub const EFI_MAX_MEMORY_TYPE: EFI_MEMORY_TYPE = 16;
