use crate::uefi::data_type::basic_type::EFI_GRAPHICS_OUTPUT_BLT_OPERATION;

pub const EFI_BLT_VIDEO_FILL: EFI_GRAPHICS_OUTPUT_BLT_OPERATION = 0;
pub const EFI_BLT_VIDEO_TO_BLT_BUFFER: EFI_GRAPHICS_OUTPUT_BLT_OPERATION = 1;
pub const EFI_BLT_BUFFER_TO_VIDEO: EFI_GRAPHICS_OUTPUT_BLT_OPERATION = 2;
pub const EFI_BLT_VIDEO_TO_VIDEO: EFI_GRAPHICS_OUTPUT_BLT_OPERATION = 3;
pub const EFI_GRAPHICS_OUTPUT_BLT_OPERATION_MAX: EFI_GRAPHICS_OUTPUT_BLT_OPERATION = 4;
